#! /bin/bash

function usage() {
    echo "Usage: $0 <file>"
}

# Parse options
while getopts "h" arg; do
    case $arg in
        h)
            usage
            echo ""
            exit 0
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

if [ $# -ne 1 ]; then
    usage
    exit 1
fi

impact -batch < <<EOF
setMode -bs
setCable -p auto
setcablespeed -speed 12000000
identify
assignFile -p 2 -file "$1"
program -p 2
quit
EOF