#! /bin/bash

function usage() {
    echo "Usage: $0 <file>"
}

if [ -z "$BLASTER_TYPE" ]; then
    BLASTER_TYPE=USB-Blaster
fi

# Parse options
while getopts "h" arg; do
    case $arg in
        h)
            usage
            echo ""
            echo "The environment variable BLASTER_TYPE sets the configuration cable type."
            exit 0
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

if [ $# -ne 1 ]; then
    usage
    exit 1
fi

quartus_pgm -c $BLASTER_TYPE -m JTAG $1
