/*
    A small test program testing the communication between patmos processors
    through the NoC

    Authors: Rasmus Bo Sørensen
             Wolfgang Puffitsch
    Copyright: DTU, BSD License
*/

#include <string.h>
#include <machine/spm.h>

const int NOC_MASTER = 0;
#include "libnoc/noc.h" // Init.h is auto generated by Poseidon the T-CREST scheduler
                  // https://github.com/t-crest/poseidon.git
#include "patio.h"

#include "bootable.h"

static const struct network_interface
{
    volatile _SPM int *dma;
    volatile _SPM int *dma_p;
    volatile _SPM int *st;
    volatile _SPM int *spm;
} ni = {
    (volatile _SPM int *) 0xE0000000,
    (volatile _SPM int *) 0xE1000000,
    (volatile _SPM int *) 0xE2000000,
    (volatile _SPM int *) 0xE8000000
};

/* Writes the content of the com spm to the UART */
void print_stat(){
    char tmp[NOC_CORES*3];
    int k;
    for(k = 1; k < NOC_CORES*3; k++)
    {
        tmp[k-1] = *(ni.spm+2*k);
        if(tmp[k-1] < 'A'){
            tmp[k-1] = '@';
        }
    }
    WRITE(tmp,NOC_CORES*3-1);
    WRITE("\n",1);
    return;
}

int wait(int amount){
    int i = 0;
    while(i <= amount){
        i++;
        char c[1];
        c[0]=CORE_ID;
    }
    return i;
}

int main(int argc, char **argv) {
    //WRITE("Hello cmp world!\n",17);

    volatile int *dummy = (int *) 0x123;

    int k,l;
    // Clear communication scratch pad
    for(k = 0; k < NOC_CORES*4; k++)
    {
        *(ni.spm+k) = 0;
    }

    if (CORE_ID == 0)
    {
        //WRITE("MASTER START\n", 13);
        
        // Wait for messages from NOC_cores
        for(k = 1; k < NOC_CORES; k++)
        {
            while(*(ni.spm+2*k) == 0){
                print_stat();

            }
        }

        // Send a hello world message
        const char *msg = "Hello world ";
        WRITE(msg, strlen(msg));
        char cid[NOC_CORES];
        for(k = 1; k < NOC_CORES; k++)
        {
            cid[k-1] = *(ni.spm+2*k);
        }
        WRITE(cid,NOC_CORES-1);
        WRITE("\n",1);

        // Blinking lights
        int i, j;
        for (;;)
        {
            UART_DATA = '1';
            for (i=2000; i!=0; --i)
                for (j=2000; j!=0; --j)
                    LEDS = 1;


            UART_DATA = '0';
            for (i=2000; i!=0; --i)
                for (j=2000; j!=0; --j)
                    LEDS = 0;

        }
    }
    else
    {
        //WRITE("SLAVES START\n", 13);
        // Send the own id to processor 0
        //wait(CORE_ID*10);
        for (;;)
        {
            *(ni.spm) = CORE_ID+'A';
            while(!noc_dma(0, CORE_ID, 0, 1));
            //WRITE("SLAVES START\n", 13);
        }
    }

    return 0;
}

