
/*
 * Generic definitions for OCP
 *
 * Authors: Wolfgang Puffitsch (wpuffitsch@gmail.com)
 *
 */

package ocp

import Chisel._

// Constants for MCmd
object OcpCmd {
  val IDLE = Bits("b000")
  val WR   = Bits("b001")
  val RD   = Bits("b010")
//  val RDEX = Bits("b011")
//  val RDL  = Bits("b100")
//  val WRNP = Bits("b101")
//  val WRC  = Bits("b110")
//  val BCST = Bits("b111")
}

// Constants for SResp
object OcpResp {
  val NULL = Bits("b00")
  val DVA  = Bits("b01")
  val FAIL = Bits("b10")
  val ERR  = Bits("b11")
}

// MS: would like fields (e.g. data) to start with lower case.
// Just classes start with upper case.

// Signals generated by master
class OcpMasterSignals(addrWidth : Int, dataWidth : Int) extends Bundle() {
  val Cmd = Bits(width = 3)
  val Addr = Bits(width = addrWidth)
  val Data = Bits(width = dataWidth)

  // This does not really clone, but Data.clone doesn't either
  override def clone() = {
    val res = new OcpMasterSignals(addrWidth, dataWidth)
    res.asInstanceOf[this.type]
  }
}

// Signals generated by slave
class OcpSlaveSignals(dataWidth : Int) extends Bundle() {
  val Resp = Bits(width = 2)
  val Data = Bits(width = dataWidth)

  // This does not really clone, but Data.clone doesn't either
  override def clone() = {
    val res = new OcpSlaveSignals(dataWidth)
    res.asInstanceOf[this.type]
  }
}
