#include <stdio.h>
#include <math.h>

#include "rosace_tasks.h"
/*
 * The following include file is generated by the Prelude compiler
 * Theoretically we should include main node specific include
 * i.e. assemblage_vX.h but we know that every main node
 * assemblage, assemblage_v2, assemblage_v3, etc... share the
 * very same data type.
 */
// #include "assemblage.h"

/* Period/Frequency of the nodes */
// const double Ts_h    = 1.0/50.0;
// const double Ts_K1   = 1.0/50.0;
// const double Ts_K2   = 1.0/50.0;
// const double Ts_f_Va = 1.0/100.0;
// const double Ts_f_Vz = 1.0/100.0;
// const double Ts_f_q  = 1.0/100.0;
// const double Ts_f_az = 1.0/100.0;
// const double Ts_f_h  = 1.0/100.0;
const double dt      = 1.0/200.0;
const double dt_de   = 1.0/200.0;
const double dt_dx   = 1.0/200.0;

/* Controller parameters */
/* Altitude hold */
const double Kp_h     =  0.1014048;
const double Ki_h     =  0.0048288;
const double h_switch =  50.0;

const double Vz_c     = -2.5;
const double Va_c     =  0.0;
const double h_c      =  11000;

/* Va Speed controller */

// const double K1_intVa =  0.06018;
// const double K1_Va    = -0.53115;
// const double K1_Vz    = -0.08956;
// const double K1_q     =  24.44890;

const double K1_intVa =  0.049802610664357;
const double K1_Va    = -0.486813084356079;
const double K1_Vz    = -0.077603095495388;
const double K1_q     = 21.692383376322041;

/* Vz Speed controller */

// const double K2_intVz =  0.0006545;
// const double K2_Vz    = -0.0031107;
// const double K2_q     =  0.4490749;
// const double K2_az    = -0.0002038;

const double K2_intVz =  0.000627342822264;
const double K2_Vz    = -0.003252836726554;
const double K2_q     =  0.376071446897134;
const double K2_az    = -0.001566907423747;


/* Trimming parameters */
const double h_eq       = 10000.0;
const double Va_eq      = 230.0;
const double Vz_eq      = 0.0;
const double alpha_eq   = 0.026485847681737;
const double theta_eq   = 0.026485847681737;

/* Atmosphere parameters */
const double rho0 =  1.225;
const double g0   =  9.80665;
const double T0_0 =  288.15;
const double T0_h = -0.0065;
const double Rs   =  287.05;

/* Aircraft parameters */
const double masse     =  57837.5;
const double I_y       =  3781272.0;
const double S         =  122.6;
const double cbar      =  4.29;
const double CD_0      =  0.016;
const double CD_alpha  =  2.5;
const double CD_deltae =  0.05;
const double CL_alpha  =  5.5;
const double CL_deltae =  0.193;
const double alpha_0   = -0.05;
const double Cm_0      =  0.04;
const double Cm_alpha  = -0.83;
const double Cm_deltae = -1.5;
const double Cm_q      = -30;

/* in-memory buffer for traces */
double sample[SPL_SIZE][NBMAX_SAMPLE];
static unsigned long instant=0;
static unsigned long sample_instant=0;

#define FMTFLOAT "%5.15f"

void print_inmemory_sample() {
  printf("# Found <%lu> samples in memory.\n",sample_instant);
  for (int i=0;i<sample_instant;++i) {
    printf(" %3.4f ",sample[SPL_T][i]);
    printf(","FMTFLOAT "," FMTFLOAT "," FMTFLOAT "," FMTFLOAT "," FMTFLOAT " ",
           sample[SPL_VA][i],
           sample[SPL_AZ][i],
           sample[SPL_Q][i],
           sample[SPL_VZ][i],
           sample[SPL_H][i]);
    printf(","FMTFLOAT" ",sample[SPL_DELTA_TH_C][i]);
    printf(","FMTFLOAT" ",sample[SPL_DELTA_E_C][i]);
    printf("\n");
  }
}

void print_simulator_outs_t(struct aircraft_dynamics_outs_t *outputs) {
#ifndef NO_PRINT
  printf(" %3.4f ",sample[SPL_T][sample_instant]);
  printf(","FMTFLOAT "," FMTFLOAT "," FMTFLOAT "," FMTFLOAT "," FMTFLOAT " ",
         outputs->Va,
         outputs->az,
         outputs->q,
         outputs->Vz,
         outputs->h);
  printf(","FMTFLOAT" ",sample[SPL_DELTA_TH_C][sample_instant-1]);
  printf(","FMTFLOAT" ",sample[SPL_DELTA_E_C][sample_instant-1]);
  printf("\n");
#endif
#ifdef INMEMORY_SAMPLE
  sample[SPL_VA][sample_instant]=outputs->Va;
  sample[SPL_AZ][sample_instant]=outputs->az;
  sample[SPL_Q][sample_instant]=outputs->q;
  sample[SPL_VZ][sample_instant]=outputs->Vz;
  sample[SPL_H][sample_instant]=outputs->h;
#endif
}

/* Va filter 100 Hz */
double
Va_filter_100(double Va) {
    static double y  = 0.0;
    static double x1 = 0.0, x2 = 0.0;
    static double x1_tmp = 0.0, x2_tmp = 0.0;
    static unsigned short debut = 1;
    /* 100 Hz coefficients */
    static double a0 = 0.956543675476034,    a1 = -1.955578398054313;
    static double b0 = 0.000479064865372430, b1 =  0.000486212556348925;

    if (debut) {
        debut  = 0;
        x1     = Va_eq * (1.0 + a1 - b1);
        x2     = Va_eq;
    }
    // Output
    y = x2;
    // State
    x1_tmp =     - a0 * x2 + b0 * Va;
    x2_tmp =  x1 - a1 * x2 + b1 * Va;
    // Update
    x1 = x1_tmp;
    x2 = x2_tmp;

    return y;
} /* end of Va filter 100 Hz */

/* Va filter 50 Hz */
double
Va_filter_50(double Va) {
    static double y  = 0.0;
    static double x1 = 0.0, x2 = 0.0;
    static double x1_tmp = 0.0, x2_tmp = 0.0;
    static unsigned short debut = 1;
    /* 50 Hz coefficients */
    static double a0 = 0.914975803093201,    a1 = -1.911199519984605;
    static double b0 = 0.001860178914816,    b1 =  0.001916104193780;

    if (debut) {
        debut  = 0;
        x1     = Va_eq * (1.0 + a1 - b1);
        x2     = Va_eq;
    }
    // Output
    y = x2;
    // State
    x1_tmp =     - a0 * x2 + b0 * Va;
    x2_tmp =  x1 - a1 * x2 + b1 * Va;
    // Update
    x1 = x1_tmp;
    x2 = x2_tmp;

    return y;
} /* end of Va filter 50 Hz */

/* Va filter 33 Hz */
double
Va_filter_33(double Va) {
    static double y  = 0.0;
    static double x1 = 0.0, x2 = 0.0;
    static double x1_tmp = 0.0, x2_tmp = 0.0;
    static unsigned short debut = 1;
    /* 33 Hz coefficients */
    static double a0 = 0.874036784828483,    a1 = -1.865563793814790;
    static double b0 = 0.004141433623051,    b1 =  0.004331557390642;

    if (debut) {
        debut  = 0;
        x1     = Va_eq * (1.0 + a1 - b1);
        x2     = Va_eq;
    }
    // Output
    y = x2;
    // State
    x1_tmp =     - a0 * x2 + b0 * Va;
    x2_tmp =  x1 - a1 * x2 + b1 * Va;
    // Update
    x1 = x1_tmp;
    x2 = x2_tmp;

    return y;
} /* end of Va filter 33 Hz */

/* Va filter 25 Hz */
double
Va_filter_25(double Va) {
    static double y  = 0.0;
    static double x1 = 0.0, x2 = 0.0;
    static double x1_tmp = 0.0, x2_tmp = 0.0;
    static unsigned short debut = 1;
    /* 25 Hz coefficients */
    static double a0 = 0.837180720246048,    a1 = -1.822731999002980;
    static double b0 = 0.007010380719078,    b1 =  0.007438340523990;

    if (debut) {
        debut  = 0;
        x1     = Va_eq * (1.0 + a1 - b1);
        x2     = Va_eq;
    }
    // Output
    y = x2;
    // State
    x1_tmp =     - a0 * x2 + b0 * Va;
    x2_tmp =  x1 - a1 * x2 + b1 * Va;
    // Update
    x1 = x1_tmp;
    x2 = x2_tmp;

    return y;
} /* end of Va filter 25 Hz */


/* Vz filter 100 Hz */
double
Vz_filter_100(double Vz) {
    static double y  = 0.0;
    static double x1 = 0.0, x2 = 0.0;
    static double x1_tmp = 0.0, x2_tmp = 0.0;
    static unsigned short debut = 1;
    /* 100 Hz coefficients */
    static double a0 = 0.956543675476034,    a1 = -1.955578398054313;
    static double b0 = 0.000479064865372430, b1 =  0.000486212556348925;

    if (debut) {
        debut  = 0;
        x1     = 0.0;
        x2     = 0.0;
    }
    // Output
    y = x2;
    // State
    x1_tmp =     - a0 * x2 + b0 * Vz;
    x2_tmp =  x1 - a1 * x2 + b1 * Vz;
    // Update
    x1 = x1_tmp;
    x2 = x2_tmp;

    return y;
} /* end of Vz filter 100 Hz */

/* Vz filter 50 Hz */
double
Vz_filter_50(double Vz) {
    static double y  = 0.0;
    static double x1 = 0.0, x2 = 0.0;
    static double x1_tmp = 0.0, x2_tmp = 0.0;
    static unsigned short debut = 1;
    /* 50 Hz coefficients */
    static double a0 = 0.914975803093201,    a1 = -1.911199519984605;
    static double b0 = 0.001860178914816,    b1 =  0.001916104193780;

    if (debut) {
        debut  = 0;
        x1     = 0.0;
        x2     = 0.0;
    }
    // Output
    y = x2;
    // State
    x1_tmp =     - a0 * x2 + b0 * Vz;
    x2_tmp =  x1 - a1 * x2 + b1 * Vz;
    // Update
    x1 = x1_tmp;
    x2 = x2_tmp;

    return y;
} /* end of Vz filter 50 Hz */

/* Vz filter 33 Hz */
double
Vz_filter_33(double Vz) {
    static double y  = 0.0;
    static double x1 = 0.0, x2 = 0.0;
    static double x1_tmp = 0.0, x2_tmp = 0.0;
    static unsigned short debut = 1;
    /* 33 Hz coefficients */
    static double a0 = 0.874036784828483,    a1 = -1.865563793814790;
    static double b0 = 0.004141433623051,    b1 =  0.004331557390642;

    if (debut) {
        debut  = 0;
        x1     = 0.0;
        x2     = 0.0;
    }
    // Output
    y = x2;
    // State
    x1_tmp =     - a0 * x2 + b0 * Vz;
    x2_tmp =  x1 - a1 * x2 + b1 * Vz;
    // Update
    x1 = x1_tmp;
    x2 = x2_tmp;

    return y;
} /* end of Vz filter 33 Hz */

/* Vz filter 25 Hz */
double
Vz_filter_25(double Vz) {
    static double y  = 0.0;
    static double x1 = 0.0, x2 = 0.0;
    static double x1_tmp = 0.0, x2_tmp = 0.0;
    static unsigned short debut = 1;
    /* 25 Hz coefficients */
    static double a0 = 0.837180720246048,    a1 = -1.822731999002980;
    static double b0 = 0.007010380719078,    b1 =  0.007438340523990;

    if (debut) {
        debut  = 0;
        x1     = 0.0;
        x2     = 0.0;
    }
    // Output
    y = x2;
    // State
    x1_tmp =     - a0 * x2 + b0 * Vz;
    x2_tmp =  x1 - a1 * x2 + b1 * Vz;
    // Update
    x1 = x1_tmp;
    x2 = x2_tmp;

    return y;
} /* end of Vz filter 25 Hz */

/* q filter 100 Hz */
double
q_filter_100(double q){
    static double y  = 0.0;
    static double x1 = 0.0, x2 = 0.0;
    static double x1_tmp = 0.0, x2_tmp = 0.0;
    static unsigned short debut = 1;
    /* 100 Hz coefficients */
    static double a0 = 0.766000101841272, a1 = -1.734903205885821;
    static double b0 = 0.014857648981438, b1 =  0.016239246974013;

    if (debut) {
        debut  = 0;
        x1     = 0.0;
        x2     = 0.0;
    }
    // Output
    y = x2;
    // State
    x1_tmp =     - a0 * x2 + b0 * q;
    x2_tmp =  x1 - a1 * x2 + b1 * q;
    // Update
    x1 = x1_tmp;
    x2 = x2_tmp;

    return y;
} /* end of q filter 100 Hz */

/* q filter 50 Hz */
double
q_filter_50(double q){
    static double y  = 0.0;
    static double x1 = 0.0, x2 = 0.0;
    static double x1_tmp = 0.0, x2_tmp = 0.0;
    static unsigned short debut = 1;
    /* 50 Hz coefficients */
    static double a0 = 0.586756156020839, a1 = -1.477888930110354;
    static double b0 = 0.049596808318647, b1 =  0.059270417591839;

    if (debut) {
        debut  = 0;
        x1     = 0.0;
        x2     = 0.0;
    }
    // Output
    y = x2;
    // State
    x1_tmp =     - a0 * x2 + b0 * q;
    x2_tmp =  x1 - a1 * x2 + b1 * q;
    // Update
    x1 = x1_tmp;
    x2 = x2_tmp;

    return y;
} /* end of q filter 50 Hz */

/* q filter 33 Hz */
double
q_filter_33(double q){
    static double y  = 0.0;
    static double x1 = 0.0, x2 = 0.0;
    static double x1_tmp = 0.0, x2_tmp = 0.0;
    static unsigned short debut = 1;
    /* 33 Hz coefficients */
    static double a0 = 0.445839214374383, a1 = -1.227970132817902;
    static double b0 = 0.094268996251840, b1 =  0.123600085304640;

    if (debut) {
        debut  = 0;
        x1     = 0.0;
        x2     = 0.0;
    }
    // Output
    y = x2;
    // State
    x1_tmp =     - a0 * x2 + b0 * q;
    x2_tmp =  x1 - a1 * x2 + b1 * q;
    // Update
    x1 = x1_tmp;
    x2 = x2_tmp;

    return y;
} /* end of q filter 33 Hz */

/* q filter 25 Hz */
double
q_filter_25(double q){
    static double y  = 0.0;
    static double x1 = 0.0, x2 = 0.0;
    static double x1_tmp = 0.0, x2_tmp = 0.0;
    static unsigned short debut = 1;
    /* 25 Hz coefficients */
    static double a0 = 0.344282786628352, a1 = -1.010643377701049;
    static double b0 = 0.137177088974822, b1 =  0.196462319952482;

    if (debut) {
        debut  = 0;
        x1     = 0.0;
        x2     = 0.0;
    }
    // Output
    y = x2;
    // State
    x1_tmp =     - a0 * x2 + b0 * q;
    x2_tmp =  x1 - a1 * x2 + b1 * q;
    // Update
    x1 = x1_tmp;
    x2 = x2_tmp;

    return y;
} /* end of q filter 25 Hz */

/* az filter 100 Hz */
double
az_filter_100(double az){
    static double y  = 0.0;
    static double x1 = 0.0, x2 = 0.0;
    static double x1_tmp = 0.0, x2_tmp = 0.0;
    static unsigned short debut = 1;
    /* 100 Hz coefficient */
    static double a0 = 0.411240701442774, a1 = -1.158045899830964;
    static double b0 = 0.107849979167580, b1 =  0.145344822444230;

    if (debut) {
        debut  = 0;
        x1     = 0.0;
        x2     = 0.0;
    }
    // Output
    y = x2;
    // State
    x1_tmp =     - a0 * x2 + b0 * az;
    x2_tmp =  x1 - a1 * x2 + b1 * az;
    // Update
    x1 = x1_tmp;
    x2 = x2_tmp;

    return y;
} /* end of az filter 100 Hz */

/* az filter 50 Hz */
double
az_filter_50(double az){
    static double y  = 0.0;
    static double x1 = 0.0, x2 = 0.0;
    static double x1_tmp = 0.0, x2_tmp = 0.0;
    static unsigned short debut = 1;
    /* 50 Hz coefficients */
    static double a0 = 0.169118914523145, a1 = -0.518588903229759;
    static double b0 = 0.229019233988375, b1 =  0.421510777305010;

    if (debut) {
        debut  = 0;
        x1     = 0.0;
        x2     = 0.0;
    }
    // Output
    y = x2;
    // State
    x1_tmp =     - a0 * x2 + b0 * az;
    x2_tmp =  x1 - a1 * x2 + b1 * az;
    // Update
    x1 = x1_tmp;
    x2 = x2_tmp;

    return y;
} /* end of az filter 50 Hz */

/* az filter 33 Hz */
double
az_filter_33(double az){
    static double y  = 0.0;
    static double x1 = 0.0, x2 = 0.0;
    static double x1_tmp = 0.0, x2_tmp = 0.0;
    static unsigned short debut = 1;
    /* 33 Hz coefficients */
    static double a0 = 0.067700864731348, a1 = -0.115832026705568;
    static double b0 = 0.263451167882487, b1 =  0.688417670143293;

    if (debut) {
        debut  = 0;
        x1     = 0.0;
        x2     = 0.0;
    }
    // Output
    y = x2;
    // State
    x1_tmp =     - a0 * x2 + b0 * az;
    x2_tmp =  x1 - a1 * x2 + b1 * az;
    // Update
    x1 = x1_tmp;
    x2 = x2_tmp;

    return y;
} /* end of az filter 33 Hz */

/* az filter 25 Hz */
double
az_filter_25(double az){
    static double y  = 0.0;
    static double x1 = 0.0, x2 = 0.0;
    static double x1_tmp = 0.0, x2_tmp = 0.0;
    static unsigned short debut = 1;
    /* 25 Hz coefficients */
    static double a0 = 0.028601207249487, a1 =  0.069303378493245;
    static double b0 = 0.228783762747218, b1 =  0.869120822995514;

    if (debut) {
        debut  = 0;
        x1     = 0.0;
        x2     = 0.0;
    }
    // Output
    y = x2;
    // State
    x1_tmp =     - a0 * x2 + b0 * az;
    x2_tmp =  x1 - a1 * x2 + b1 * az;
    // Update
    x1 = x1_tmp;
    x2 = x2_tmp;

    return y;
} /* end of az filter 25 Hz */

/* h filter 100 Hz*/
double
h_filter_100(double h){
    static double y  = 0.0;
    static double x1 = 0.0, x2 = 0.0;
    static double x1_tmp = 0.0, x2_tmp = 0.0;
    static unsigned short debut = 1;
    /* 100 Hz coefficients */
    static double a0 = 0.766000101841272, a1 = -1.734903205885821;
    static double b0 = 0.014857648981438, b1 =  0.016239246974013;

    if (debut) {
        debut  = 0;
        x1     = h_eq * (1.0 + a1 - b1);
        x2     = h_eq;
    }
    // Output
    y = x2;
    // State
    x1_tmp =     - a0 * x2 + b0 * h;
    x2_tmp =  x1 - a1 * x2 + b1 * h;
    // Update
    x1 = x1_tmp;
    x2 = x2_tmp;

    return y;
} /* end of h filter 100 Hz */

/* h filter 50 Hz*/
double
h_filter_50(double h){
    static double y  = 0.0;
    static double x1 = 0.0, x2 = 0.0;
    static double x1_tmp = 0.0, x2_tmp = 0.0;
    static unsigned short debut = 1;
    /* 50 Hz coefficients */
    static double a0 = 0.586756156020839, a1 = -1.477888930110354;
    static double b0 = 0.049596808318647, b1 =  0.059270417591839;

    if (debut) {
        debut  = 0;
        x1     = h_eq * (1.0 + a1 - b1);
        x2     = h_eq;
    }
    // Output
    y = x2;
    // State
    x1_tmp =     - a0 * x2 + b0 * h;
    x2_tmp =  x1 - a1 * x2 + b1 * h;
    // Update
    x1 = x1_tmp;
    x2 = x2_tmp;

    return y;
} /* end of h filter 50 Hz */

/* h filter 33 Hz*/
double h_filter_33(double h){
    static double y  = 0.0;
    static double x1 = 0.0, x2 = 0.0;
    static double x1_tmp = 0.0, x2_tmp = 0.0;
    static unsigned short debut = 1;
    /* 33 Hz coefficients */
    static double a0 = 0.445839214374383, a1 = -1.227970132817902;
    static double b0 = 0.094268996251840, b1 =  0.123600085304640;

    if (debut) {
        debut  = 0;
        x1     = h_eq * (1.0 + a1 - b1);
        x2     = h_eq;
    }
    // Output
    y = x2;
    // State
    x1_tmp =     - a0 * x2 + b0 * h;
    x2_tmp =  x1 - a1 * x2 + b1 * h;
    // Update
    x1 = x1_tmp;
    x2 = x2_tmp;

    return y;
} /* end of h filter 33 Hz */

/* h filter 25 Hz*/
double h_filter_25(double h){
    static double y  = 0.0;
    static double x1 = 0.0, x2 = 0.0;
    static double x1_tmp = 0.0, x2_tmp = 0.0;
    static unsigned short debut = 1;
    /* 25 Hz coefficients */
    static double a0 = 0.344282786628352, a1 = -1.010643377701049;
    static double b0 = 0.137177088974822, b1 =  0.196462319952482; /**/

    if (debut) {
        debut  = 0;
        x1     = h_eq * (1.0 + a1 - b1);
        x2     = h_eq;
    }
    // Output
    y = x2;
    // State
    x1_tmp =     - a0 * x2 + b0 * h;
    x2_tmp =  x1 - a1 * x2 + b1 * h;
    // Update
    x1 = x1_tmp;
    x2 = x2_tmp;

    return y;
} /* end of h filter 25 Hz */


/* Altitude hold controller 50 Hz */
double altitude_hold_50(double h_f, double h_c){
    static double y = 0.0;
    static double Ts_h = 1.0/50.0;
    static double integrator = 532.2730285;

    if ((h_f - h_c) < -50) {
        // Output
        y = Vz_c;
    }
    else if ((h_f - h_c) > 50) {
        // Output
        y = -Vz_c;
    }
    else {
        // Output
        y = Kp_h * (h_f - h_c) + Ki_h * integrator;
        // State
        integrator += Ts_h * (h_f - h_c);
    }

    return y;
}

/* Altitude hold controller 33 Hz */
double altitude_hold_33(double h_f, double h_c){
    static double y = 0.0;
    static double Ts_h = 1.0/33.0;
    static double integrator = 532.2730285;

    if ((h_f - h_c) < -50) {
        // Output
        y = Vz_c;
    }
    else if ((h_f - h_c) > 50) {
        // Output
        y = -Vz_c;
    }
    else {
        // Output
        y = Kp_h * (h_f - h_c) + Ki_h * integrator;
        // State
        integrator += Ts_h * (h_f - h_c);
    }

    return y;
}

/* Altitude hold controller 25 Hz */
double altitude_hold_25(double h_f, double h_c){
    static double y = 0.0;
    static double Ts_h = 1.0/25.0;
    static double integrator = 532.2730285;

    if ((h_f - h_c) < -50) {
        // Output
        y = Vz_c;
    }
    else if ((h_f - h_c) > 50) {
        // Output
        y = -Vz_c;
    }
    else {
        // Output
        y = Kp_h * (h_f - h_c) + Ki_h * integrator;
        // State
        integrator += Ts_h * (h_f - h_c);
    }

    return y;
}

/* Altitude hold controller 10 Hz */
double altitude_hold_10(double h_f, double h_c){
    static double y = 0.0;
    static double Ts_h = 1.0/10.0;
    static double integrator = 532.2730285;

    if ((h_f - h_c) < -50) {
        // Output
        y = Vz_c;
    }
    else if ((h_f - h_c) > 50) {
        // Output
        y = -Vz_c;
    }
    else {
        // Output
        y = Kp_h * (h_f - h_c) + Ki_h * integrator;
        // State
        integrator += Ts_h * (h_f - h_c);
    }

    return y;
}

/* Va Speed controller 50 Hz */
double Va_control_50(double Va_f, double Vz_f, double q_f, double Va_c){
    static double y = 0.0;
    static double Ts_K1 = 1.0/50.0;
    static double integrator = 0.0;

    // Output
    y = K1_intVa * integrator + K1_Va * (Va_f - Va_eq) + K1_Vz * Vz_f + K1_q * q_f + delta_th_eq;
    // State
    integrator += Ts_K1 * (Va_c - Va_f + Va_eq);

    return y;
}

/* Va Speed controller 33 Hz */
double Va_control_33(double Va_f, double Vz_f, double q_f, double Va_c){
    static double y = 0.0;
    static double Ts_K1 = 1.0/33.0;
    static double integrator = 0.0;

    // Output
    y = K1_intVa * integrator + K1_Va * (Va_f - Va_eq) + K1_Vz * Vz_f + K1_q * q_f + delta_th_eq;
    // State
    integrator += Ts_K1 * (Va_c - Va_f + Va_eq);

    return y;
}

/* Va Speed controller 25 Hz */
double Va_control_25(double Va_f, double Vz_f, double q_f, double Va_c){
    static double y = 0.0;
    static double Ts_K1 = 1.0/25.0;
    static double integrator = 0.0;

    // Output
    y = K1_intVa * integrator + K1_Va * (Va_f - Va_eq) + K1_Vz * Vz_f + K1_q * q_f + delta_th_eq;
    // State
    integrator += Ts_K1 * (Va_c - Va_f + Va_eq);

    return y;
}

/* Va Speed controller 10 Hz */
double Va_control_10(double Va_f, double Vz_f, double q_f, double Va_c){
    static double y = 0.0;
    static double Ts_K1 = 1.0/10.0;
    static double integrator = 0.0;

    // Output
    y = K1_intVa * integrator + K1_Va * (Va_f - Va_eq) + K1_Vz * Vz_f + K1_q * q_f + delta_th_eq;
    // State
    integrator += Ts_K1 * (Va_c - Va_f + Va_eq);

    return y;
}

/* Vz Speed controller 50 Hz */
double Vz_control_50(double Vz_f, double Vz_c, double q_f, double az_f){
    static double y = 0.0;
    static double Ts_K2 = 1.0/50.0;
    static double integrator = 0.0;

    // Output
    y = K2_intVz * integrator + K2_Vz * Vz_f + K2_q * q_f + K2_az * az_f + delta_e_eq;
    // State
    integrator += Ts_K2 * (Vz_c - Vz_f);

    return y;
}

/* Vz Speed controller 33 Hz */
double Vz_control_33(double Vz_f, double Vz_c, double q_f, double az_f){
    static double y = 0.0;
    static double Ts_K2 = 1.0/33.0;
    static double integrator = 0.0;

    // Output
    y = K2_intVz * integrator + K2_Vz * Vz_f + K2_q * q_f + K2_az * az_f + delta_e_eq;
    // State
    integrator += Ts_K2 * (Vz_c - Vz_f);

    return y;
}

/* Vz Speed controller 25 Hz */
double Vz_control_25(double Vz_f, double Vz_c, double q_f, double az_f){
    static double y = 0.0;
    static double Ts_K2 = 1.0/25.0;
    static double integrator = 0.0;

    // Output
    y = K2_intVz * integrator + K2_Vz * Vz_f + K2_q * q_f + K2_az * az_f + delta_e_eq;
    // State
    integrator += Ts_K2 * (Vz_c - Vz_f);

    return y;
}

/* Vz Speed controller 10 Hz */
double Vz_control_10(double Vz_f, double Vz_c, double q_f, double az_f){
    static double y = 0.0;
    static double Ts_K2 = 1.0/10.0;
    static double integrator = 0.0;

    // Output
    y = K2_intVz * integrator + K2_Vz * Vz_f + K2_q * q_f + K2_az * az_f + delta_e_eq;
    // State
    integrator += Ts_K2 * (Vz_c - Vz_f);

    return y;
}

/* Engine */
double engine(double delta_th_c) {

    static double y      = delta_th_eq;
    static double x1     = delta_th_eq;
    static double x1_dot = 0.0;
    static double tau    = 0.75;

    // Output
    y = 26350.0 * x1;
    // State Equation
    x1_dot = -tau * x1 + tau * delta_th_c;
    // Update State
    x1 += dt_dx * x1_dot;

    return y;
}

/* Elevator */
double elevator(double delta_e_c) {

    static double y  = delta_e_eq;
    static double x1 = delta_e_eq, x2 = 0.0;
    static double x1_dot = 0.0, x2_dot = 0.0;
    static double omega = 25.0, xi = 0.85;

    // Output
    y = x1;
    // State Equation
    x1_dot = x2;
    x2_dot = -omega * omega * x1 - 2.0 * xi * omega * x2 + omega * omega * delta_e_c;
    // Update State
    x1 += dt_de * x1_dot;
    x2 += dt_de * x2_dot;

    return y;
}


/* Flight dynamics */
void aircraft_dynamics (double delta_e, double T,  struct aircraft_dynamics_outs_t *outputs){

    static int debut = 1;

    static double u = 0.0, w = 0.0, q = 0.0, theta = 0.0, h = 0.0;
    static double u_dot = 0.0, w_dot = 0.0, q_dot = 0.0, theta_dot = 0.0, h_dot = 0.0;

    static double CD = 0.0, CL = 0.0, Cm = 0.0;
    static double Xa = 0.0, Za = 0.0, Ma = 0.0;

    static double alpha = 0.0, qbar = 0.0, V = 0.0, rho = 0.0;

    if (debut) {
        debut = 0;
        u     = Va_eq * cos(theta_eq);
        w     = Va_eq * sin(theta_eq);
        q     = 0.0;
        theta = theta_eq;
        h     = h_eq;
    }

    rho   = rho0 * pow(1.0 + T0_h / T0_0 * h,- g0 / (Rs * T0_h) - 1.0);
    alpha = atan(w/u);
    V     = sqrt(u * u + w * w);
    qbar  = 0.5 * rho * V * V;
    CL    = CL_deltae * delta_e + CL_alpha * (alpha - alpha_0);
    CD    = CD_0 + CD_deltae * delta_e + CD_alpha * (alpha - alpha_0) * (alpha - alpha_0);
    Cm    = Cm_0 + Cm_deltae * delta_e + Cm_alpha * alpha + 0.5 * Cm_q * q * cbar / V;
    Xa    = - qbar * S * (CD * cos(alpha) - CL * sin(alpha));
    Za    = - qbar * S * (CD * sin(alpha) + CL * cos(alpha));
    Ma    = qbar * cbar * S * Cm;

    // Output
    outputs -> Va = V;
    outputs -> Vz = w * cos(theta) - u * sin(theta);
    outputs -> q  = q;
    outputs -> az = g0 * cos(theta) + Za / masse;
    outputs -> h  = h;
    // State Equation
    u_dot     = - g0 * sin (theta) - q * w + (Xa + T) / masse;
    w_dot     = g0 * cos (theta) + q * u + Za / masse;
    q_dot     = Ma / I_y;
    theta_dot = q;
    h_dot     = u * sin(theta) - w * cos(theta);
    // Update State
    u     += dt * u_dot;
    w     += dt * w_dot;
    q     += dt * q_dot;
    theta += dt * theta_dot;
    h     += dt * h_dot;


    static double Time = 0.0;
    if ((instant%4)==0) { /* 50Hz print */
      sample_instant++;
      sample[SPL_T][sample_instant] = Time;
      print_simulator_outs_t(outputs);
    }

    instant++;
    Time = Time + dt;
}

/*
 * The commanded altitude
 */
double input_h_c() {
  return h_c;
}

/*
 * The commanded airspeed
 */
double input_Va_c() {
  return Va_c;
}

void output_delta_th_c(double delta_th_c){
  sample[SPL_DELTA_TH_C][sample_instant] = delta_th_c;
}

void output_delta_e_c(double delta_e_c){
  sample[SPL_DELTA_E_C][sample_instant] = delta_e_c;
}