all: handbook noc libcorethread libnoc libmp

handbook:
	make -C handbook all
noc:
	make -C noc all
libcorethread:
	make -C libcorethread all
libnoc:
	make -C libnoc all
libmp:
	make -C libmp all

.PHONY: handbook noc libcorethread libnoc libmp
