--
--	patmos_rom.vhd
--
--	generic VHDL version of ROM
--
--		DONT edit this file!
--		generated by patmos.asm.Bin2Vhdl
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity patmos_rom is
port (
--	 clk : in std_logic;
    address : in std_logic_vector(8 downto 0);
    q : out std_logic_vector(31 downto 0)
);
end patmos_rom;

architecture rtl of patmos_rom is

  constant addr_width : integer := 8;
  
  type data_memory is array (0 to 2**addr_width - 1) of std_logic_vector(31 downto 0);
  signal data_mem : data_memory := (
"00000000000000000000000000000000",
"00000000000101100000000000001111",
"00000000110101101011000000011100",
"00000000000110000000000000101010",
"00000010100110001011000110000001",
"00000000000000000000000000000000",
"00000000000000000000000000000000",
"00000010110001101011011000000001",
"00000110010000000000000000000100",
"00000000000000000000000000000000",
"00000000000000000000000000000000",
"00000111100000000000000000000000",
"00000010010000000000000000100100",

    others => "00000000000000000000000000000000"
  
  );

begin
  q <= data_mem(to_integer(unsigned(address)));	

--  mem : process(clk)
--  begin
--    if (rising_edge(clk)) then
--  	  q <= data_mem(to_integer(unsigned(address)));	
--    end if;
--  end process mem;

end rtl;
