.PHONY: all
all: add vector_add fibonacci

add:
	patmos-clang -O2 test_cop_add.c -o test_cop_add.elf

vector_add:
	patmos-clang -O2 test_cop_vector_add.c -o test_cop_vector_add.elf

fibonacci:
	patmos-clang -O2 test_cop_fibonacci.c -o test_cop_fibonacci.elf