#pragma once

/*
 * This file was generated using SimpleSMTScheduler (https://github.com/egk696/SimpleSMTScheduler)
 * Generated schedule based on task set defined in examples/rosace_argo_tasks.csv
 * Scheduled Task Set Utilization = 1.049375 %
 */

#define NUM_OF_TASKS 18
#define HYPER_PERIOD 320000

#define MAPPED_CORE_COUNT 3

#define ENGINE_ID 0
#define ENGINE_PERIOD 80000
#define ELEVATOR_ID 1
#define ELEVATOR_PERIOD 80000
#define AIRCRAFT_DYN_ID 2
#define AIRCRAFT_DYN_PERIOD 80000
#define VL_AIR2FILTER_SEND_ID 3
#define VL_AIR2FILTER_SEND_PERIOD 80000
#define LOGGING_ID 4
#define LOGGING_PERIOD 80000
#define H_FILTER_ID 5
#define H_FILTER_PERIOD 160000
#define AZ_FILTER_ID 6
#define AZ_FILTER_PERIOD 160000
#define VZ_FILTER_ID 7
#define VZ_FILTER_PERIOD 160000
#define Q_FILTER_ID 8
#define Q_FILTER_PERIOD 160000
#define VA_FILTER_ID 9
#define VA_FILTER_PERIOD 160000
#define VL_FILTER2CTRL_SEND_ID 10
#define VL_FILTER2CTRL_SEND_PERIOD 160000
#define VL_FILTER2CTRL_RECV_ID 11
#define VL_FILTER2CTRL_RECV_PERIOD 160000
#define VL_CTRL2AIR_RECV_ID 12
#define VL_CTRL2AIR_RECV_PERIOD 320000
#define VL_AIR2FILTER_RECV_ID 13
#define VL_AIR2FILTER_RECV_PERIOD 320000
#define ALTI_HOLD_ID 14
#define ALTI_HOLD_PERIOD 320000
#define VZ_CONTROL_ID 15
#define VZ_CONTROL_PERIOD 320000
#define VA_CONTROL_ID 16
#define VA_CONTROL_PERIOD 320000
#define VL_CTRL2AIR_SEND_ID 17
#define VL_CTRL2AIR_SEND_PERIOD 320000

char* tasks_names[NUM_OF_TASKS] = {"ENGINE", "ELEVATOR", "AIRCRAFT_DYN", "VL_AIR2FILTER_SEND", "LOGGING", "H_FILTER", "AZ_FILTER", "VZ_FILTER", "Q_FILTER", "VA_FILTER", "VL_FILTER2CTRL_SEND", "VL_FILTER2CTRL_RECV", "VL_CTRL2AIR_RECV", "VL_AIR2FILTER_RECV", "ALTI_HOLD", "VZ_CONTROL", "VA_CONTROL", "VL_CTRL2AIR_SEND"};

unsigned tasks_per_cores[MAPPED_CORE_COUNT] = {5, 8, 5};

unsigned cores_hyperperiods[MAPPED_CORE_COUNT] = {320000, 320000, 320000};

unsigned tasks_coreids[NUM_OF_TASKS] = {0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 0, 1, 2, 2, 2, 2};

unsigned long long tasks_periods[NUM_OF_TASKS] = {ENGINE_PERIOD, ELEVATOR_PERIOD, AIRCRAFT_DYN_PERIOD, VL_AIR2FILTER_SEND_PERIOD, LOGGING_PERIOD, H_FILTER_PERIOD, AZ_FILTER_PERIOD, VZ_FILTER_PERIOD, Q_FILTER_PERIOD, VA_FILTER_PERIOD, VL_FILTER2CTRL_SEND_PERIOD, VL_FILTER2CTRL_RECV_PERIOD, VL_CTRL2AIR_RECV_PERIOD, VL_AIR2FILTER_RECV_PERIOD, ALTI_HOLD_PERIOD, VZ_CONTROL_PERIOD, VA_CONTROL_PERIOD, VL_CTRL2AIR_SEND_PERIOD};

#define ENGINE_INSTS_NUM 4
#define ELEVATOR_INSTS_NUM 4
#define AIRCRAFT_DYN_INSTS_NUM 4
#define VL_AIR2FILTER_SEND_INSTS_NUM 4
#define LOGGING_INSTS_NUM 4
#define H_FILTER_INSTS_NUM 2
#define AZ_FILTER_INSTS_NUM 2
#define VZ_FILTER_INSTS_NUM 2
#define Q_FILTER_INSTS_NUM 2
#define VA_FILTER_INSTS_NUM 2
#define VL_FILTER2CTRL_SEND_INSTS_NUM 2
#define VL_FILTER2CTRL_RECV_INSTS_NUM 2
#define VL_CTRL2AIR_RECV_INSTS_NUM 1
#define VL_AIR2FILTER_RECV_INSTS_NUM 1
#define ALTI_HOLD_INSTS_NUM 1
#define VZ_CONTROL_INSTS_NUM 1
#define VA_CONTROL_INSTS_NUM 1
#define VL_CTRL2AIR_SEND_INSTS_NUM 1

unsigned tasks_insts_counts[NUM_OF_TASKS] = {ENGINE_INSTS_NUM, ELEVATOR_INSTS_NUM, AIRCRAFT_DYN_INSTS_NUM, VL_AIR2FILTER_SEND_INSTS_NUM, LOGGING_INSTS_NUM, H_FILTER_INSTS_NUM, AZ_FILTER_INSTS_NUM, VZ_FILTER_INSTS_NUM, Q_FILTER_INSTS_NUM, VA_FILTER_INSTS_NUM, VL_FILTER2CTRL_SEND_INSTS_NUM, VL_FILTER2CTRL_RECV_INSTS_NUM, VL_CTRL2AIR_RECV_INSTS_NUM, VL_AIR2FILTER_RECV_INSTS_NUM, ALTI_HOLD_INSTS_NUM, VZ_CONTROL_INSTS_NUM, VA_CONTROL_INSTS_NUM, VL_CTRL2AIR_SEND_INSTS_NUM};

unsigned long long ENGINE_sched_insts[ENGINE_INSTS_NUM] = {0, 80000, 160000, 240000};
unsigned long long ELEVATOR_sched_insts[ELEVATOR_INSTS_NUM] = {570, 80570, 160570, 240570};
unsigned long long AIRCRAFT_DYN_sched_insts[AIRCRAFT_DYN_INSTS_NUM] = {2081, 82081, 162081, 242081};
unsigned long long VL_AIR2FILTER_SEND_sched_insts[VL_AIR2FILTER_SEND_INSTS_NUM] = {1790, 81790, 161790, 241790};
unsigned long long LOGGING_sched_insts[LOGGING_INSTS_NUM] = {0, 80000, 160000, 240000};
unsigned long long H_FILTER_sched_insts[H_FILTER_INSTS_NUM] = {7692, 167692};
unsigned long long AZ_FILTER_sched_insts[AZ_FILTER_INSTS_NUM] = {87692, 247692};
unsigned long long VZ_FILTER_sched_insts[VZ_FILTER_INSTS_NUM] = {88334, 248334};
unsigned long long Q_FILTER_sched_insts[Q_FILTER_INSTS_NUM] = {89607, 249607};
unsigned long long VA_FILTER_sched_insts[VA_FILTER_INSTS_NUM] = {88970, 248970};
unsigned long long VL_FILTER2CTRL_SEND_sched_insts[VL_FILTER2CTRL_SEND_INSTS_NUM] = {90243, 250243};
unsigned long long VL_FILTER2CTRL_RECV_sched_insts[VL_FILTER2CTRL_RECV_INSTS_NUM] = {2438, 162438};
unsigned long long VL_CTRL2AIR_RECV_sched_insts[VL_CTRL2AIR_RECV_INSTS_NUM] = {291954};
unsigned long long VL_AIR2FILTER_RECV_sched_insts[VL_AIR2FILTER_RECV_INSTS_NUM] = {250536};
unsigned long long ALTI_HOLD_sched_insts[ALTI_HOLD_INSTS_NUM] = {0};
unsigned long long VZ_CONTROL_sched_insts[VZ_CONTROL_INSTS_NUM] = {2910};
unsigned long long VA_CONTROL_sched_insts[VA_CONTROL_INSTS_NUM] = {632};
unsigned long long VL_CTRL2AIR_SEND_sched_insts[VL_CTRL2AIR_SEND_INSTS_NUM] = {1970};

unsigned long long *tasks_schedules[NUM_OF_TASKS] = {ENGINE_sched_insts, ELEVATOR_sched_insts, AIRCRAFT_DYN_sched_insts, VL_AIR2FILTER_SEND_sched_insts, LOGGING_sched_insts, H_FILTER_sched_insts, AZ_FILTER_sched_insts, VZ_FILTER_sched_insts, Q_FILTER_sched_insts, VA_FILTER_sched_insts, VL_FILTER2CTRL_SEND_sched_insts, VL_FILTER2CTRL_RECV_sched_insts, VL_CTRL2AIR_RECV_sched_insts, VL_AIR2FILTER_RECV_sched_insts, ALTI_HOLD_sched_insts, VZ_CONTROL_sched_insts, VA_CONTROL_sched_insts, VL_CTRL2AIR_SEND_sched_insts};
